export const REQUEST = "REQUEST_EXCHANGE_RATES";
export const ERROR = "REQUEST_EXCHANGE_RATES_SUCCESS";
export const SUCCESS = "REQUEST_EXCHANGE_RATES_ERROR";
export const FETCH = "FETCH_EXCHANGE_RATES";
export const DUFAULT = "DUFAULT_CURRENCY";
export const EXCHANGE = "EXCHANGE_CURRENCY";
export const FAVORITE = "FAVORITE_CURRENCY";